version: '2'

services:
  00-unzip:
    image: "yareddej/ew-shopp-00-unzip:latest"
    environment: 
      - STEP_NAME=00-unzip
      - KUBEMQ_HOST=kubemq
    volumes:
      - /bigdata/yared-experiment/00-unzip/input:/in
      - /bigdata/yared-experiment/00-unzip/work:/work
      - /bigdata/yared-experiment/00-unzip/output:/out
      - /bigdata/yared-experiment/00-unzip/sandbox:/sandbox
    command: 
      - '10'
      - /sandbox
      - /code
      - /in
      - /work
      - /out
      - '-'
      - 'MQ1'

  01-tsv2csv:
    image: "yareddej/ew-shopp-01-tsv2csv:latest"
    environment: 
      - STEP_NAME=01-tsv2csv
      - KUBEMQ_HOST=kubemq
    volumes:
      - /bigdata/yared-experiment/00-unzip/output:/in
      - /bigdata/yared-experiment/01-tsv2csv/work:/work
      - /bigdata/yared-experiment/01-tsv2csv/output:/out
      - /bigdata/yared-experiment/01-tsv2csv/sandbox:/sandbox
    command: 
      - '10'
      - /sandbox
      - /code
      - /in
      - /work
      - /out
      - 'MQ1'
      - 'MQ2'

  kubemq:
    image: kubemq/kubemq:latest
    container_name: kubemq
    ports:
      - "8080:8080"
      - "9090:9090"
      - "50000:50000"
    environment:
      - KUBEMQ_HOST=kubemq
      - KUBEMQ_TOKEN="8297ae1b-d2bc-40b4-bf95-39a67162984d"
    volumes:
      - kubemq_vol:/store

volumes:
  kubemq_vol: